### ISSUE TITLE
Multiple Lambda functions from the sam.yml file possible?

### ISSUE THREAD

**Issue by joelfogue** [awslabs/aws-serverless-samfarm#5]
I have a situation where I have multiple lambda functions within our API Gateway's API. 
I'm new to AWS and learning as much as I can.
I am wondering, how would I change the template yaml (sam.yaml) so that we can deploy to any number of lambda functions and not just one as is the case in this lab.
Would you create multiple index.js file per lambda function? 

- so index1.js -> will map to first lambda function
- index2.js -> second lambda function; 
- etc....

**_And how do I update the sam.yaml file to reflect this change?_**

Here's a snippet code of what I'm trying to accomplish:
```
Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
```
    .... and more endpoints here to hit more lambda functions? So do I create multiple index.js to map to each individual lambda function?

**Comment by andrewryan1906** [comment]
Guys,

I have the same question.

Really trying to learn serverless and questions like these - on best practices - is making it super difficult. Would love some direction here.

**Comment by dfloresgonz** [comment]
any help

**Comment by jairoVera** [comment]
As far as I am aware, you can have multiple JS files, each containing a handler to a different Lambda. The files don't have to be in the same directory! You can also define the 2nd Lambda function in the same SAM template yaml file where you defined the 1st Lambda function.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time

Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: firstsample/firstsample.handler   # firstsample.js file is in firstsample direcotory
      Role: !GetAtt BasicAWSLambdaRole.Arn
      Runtime: nodejs6.10
      CodeUri: ./                          # Look for code in the same directory as the output SAM file
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
  
  SecondSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: secondsample.handler                  # didn't have to include secondsample directory
      Role: !GetAtt BasicAWSLambdaRole.Arn
      Runtime: nodejs6.10
      CodeUri: ./secondsample           # code is in the secondsample directory, located in same directory
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TextResource
            Method: GET
```

**Comment by red8888** [comment]
This is the top google result for "sam template multiple functions". Be nice to have airoVera's solution in the official docs if thats the way we should be doing this.

And how does this work with `aws cloudformation package` and `aws cloudformation deploy` ? Do I need to run that for each lambda/CodeUri?

**Comment by joeyshub** [comment]
@red8888   what I do is having my repo structure as below. I used Jenkins pipeline to do 'npm install' for my lambda functions, FYR.

├── 00_DEVOPS-test1
│   ├── index.js
│   ├── package.json
│   ├── package-lock.json
│   └── README.md
├── 00_DEVOPS-test2
│   ├── index.js
│   ├── package.json
│   ├── package-lock.json
│   └── README.md
├── Jenkinsfile
├── packaged.yaml
├── README.md
└── template.yaml

**Comment by hugoprudente** [comment]
@red8888, using the @jairoVera approach, as both `AWS::Serverless::Function` are on the same template only one `sam package | aws cloudformation package` must be executed, same for the `deploy`.

Regarding the first code if you have a `main.js` that check the origin of the request and it can route it Post to `index-1.js` and the Get to `index-2.js` using the `main.js` handler and directing to 2 "subhandlers"

**Comment by deleugpn** [comment]
@jairoVera do you know if that approach will generate 1 or 2 API Gateways?

**Comment by sam-mundle** [comment]
It will generate two separate API gateways but the issue is (at least when generating a testing environment locally) if you create separate functions that have separate handler files both of the handler files will be written into the build folder for BOTH Lambda functions. I'm not sure if this would happen when deploying though.

![capture](https://user-images.githubusercontent.com/32434105/53127250-04fe7c80-3530-11e9-9eb5-61152da6ed56.PNG)

**Comment by sertaco** [comment]
It seems SAM is intended for one lambda per application. For multi-function applications, there is [Nested application method](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-nested-applications.html).

**Comment by red8888** [comment]
SAM does support multiple functions, the right way to do it is with the `sam build` command which pulls deps for all functions and creates a package that will be deployed as a "serverless application" 

Maybe someone from the SAM team can reiterate this?

**Comment by estebansolo** [comment]
@deleugpn it will generate two API Gateways, but you can add the API Gateway resource and It will create just one

```AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time

Resources:
  ApiResource:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod  
  
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: firstsample/firstsample.handler   # firstsample.js file is in firstsample direcotory
      Role: !GetAtt BasicAWSLambdaRole.Arn
      Runtime: nodejs6.10
      CodeUri: ./                          # Look for code in the same directory as the output SAM file
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
            RestApiId: !Ref ApiResource
  
  SecondSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: secondsample.handler                  # didn't have to include secondsample directory
      Role: !GetAtt BasicAWSLambdaRole.Arn
      Runtime: nodejs6.10
      CodeUri: ./secondsample           # code is in the secondsample directory, located in same directory
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TextResource
            Method: GET
            RestApiId: !Ref ApiResource```

**Comment by MatteoGioioso** [comment]
And how about shared libraries and code?

**Comment by estebansolo** [comment]
You can use **Layers**

**Comment by TrentonAdams** [comment]
I just don't understand why this is not supported.  Use of the nested-applications mode is a hack because AWS realized how bad their lambda -> API gateway solution was.  The very idea that I have to put every tiny piece of code in it's own lambda, with it's own dependencies, is a night mare.  Talk about massive bloat.  It's not uncommon with the simplest of node apps for node_modules to be 100M.  Have even 5 REST endpoints and you've now got 500M of deployments.

Is it really this way?  Am I missing something?

**Comment by debendraoli** [comment]
@jairoVera is life saver, I was banging on this problem for a week.

I have 13 serverless functions having go1.x and python run times and dependent to each others, previously I was managing the code bases and aws services manually, it was so pain, accidentally I discovered `sam` and  I introduced one template file for all the functions but build `sam` was unable to find the code bases.

I specified `CodeUri` where my codes points.

Now I can easily debug locally, build and deploy in one click. :-)

**Comment by javiortizmol** [comment]
> @jairoVera is life saver, I was banging on this problem for a week.
> 
> I have 13 serverless functions having go1.x and python run times and dependent to each others, previously I was managing the code bases and aws services manually, it was so pain, accidentally I discovered `sam` and I introduced one template file for all the functions but build `sam` was unable to find the code bases. Now I can easily debug locally, build and deploy in one click. :-)

So works or no? "but build sam was unable to find the code bases. Now I can easily debug locally, build and deploy in one click"

**Comment by debendraoli** [comment]
> > @jairoVera is life saver, I was banging on this problem for a week.
> > I have 13 serverless functions having go1.x and python run times and dependent to each others, previously I was managing the code bases and aws services manually, it was so pain, accidentally I discovered `sam` and I introduced one template file for all the functions but build `sam` was unable to find the code bases. Now I can easily debug locally, build and deploy in one click. :-)
> 
> So works or no? "but build sam was unable to find the code bases. Now I can easily debug locally, build and deploy in one click"

I already told. 
>> "Now I can easily debug locally, build and deploy in one click. :-)"

**Comment by gavetisyanca** [comment]
I have a different question. How do I have 1 lambda function with different events (different http methods) I don't want to create several lambda functions for each method its not interesting and not efficient. I want to be able trigger that function with either with  boolean logic inside the actual script or even better edit this serverless.yml file so I can do that from yaml rather than inside the script 
Please help me, will much appreciate that

**Comment by sromano88-svc** [comment]
> It will generate two separate API gateways but the issue is (at least when generating a testing environment locally) if you create separate functions that have separate handler files both of the handler files will be written into the build folder for BOTH Lambda functions. I'm not sure if this would happen when deploying though.
> 
> ![capture](https://user-images.githubusercontent.com/32434105/53127250-04fe7c80-3530-11e9-9eb5-61152da6ed56.PNG)

Yes, it happens when you deploy it. You can see it in the AWS Lambda console.
Were you (or someone) able to isolate the functions handlers when deploying?

In my case, when running `sam build,` it executes the npm install for each function (`Running NodejsNpmBuilder:NpmInstall`) and it takes a lot of time. This is the main issue I am trying to avoid.

**Comment by sromano88-svc** [comment]
> I have a different question. How do I have 1 lambda function with different events (different http methods) I don't want to create several lambda functions for each method its not interesting and not efficient. I want to be able trigger that function with either with boolean logic inside the actual script or even better edit this serverless.yml file so I can do that from yaml rather than inside the script
> Please help me, will much appreciate that

This is what I do:

```yml
EcommerceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ecommerce-lambda
      Handler: src/handlers/ecommerceHandler.handler
      Runtime: nodejs12.x
      Description: Products Lambda function.
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          LAMBDA_ENVIRONMENT: local
      Events:
        # Server
        GetServiceRunningAPI:
          Type: Api
          Properties:
            Path: /api/products-health-check
            Method: GET
        # Products
        GetProductsAPI:
          Type: Api
          Properties:
            Path: /api/products
            Method: GET
        GetSingleProductsAPI:
          Type: Api
          Properties:
            Path: /api/products/{productId}
            Method: GET
        PostProductsAPI:
          Type: Api
          Properties:
            Path: /api/products
            Method: POST
        PutProductsAPI:
          Type: Api
          Properties:
            Path: /api/products/{productId}
            Method: PUT
        DeleteProductsAPI:
          Type: Api
          Properties:
            Path: /api/products/{productId}
            Method: DELETE
```
